### ISSUE TITLE
[ota_http] use http_request instead of upstream arduino/HTTPClient

### ISSUE THREAD

**Issue by oarcher** [oarcher/piotech#4]
This will allow to fix #3

**Comment by cho0p** [comment]
Hi @oarcher

thank you for this component. Do you already know when you can make those changes so the component would work with the esp-idf framework?

**Comment by oarcher** [comment]
Hi @cho0p,
Hopefully, i will be able to work on it at the end of october.

**Comment by oarcher** [comment]
it will not be possible to use esphome http_request, because the http stream is not available, and it reads only text data.

**Comment by oarcher** [comment]
see #3 for esp-idf implementation
