### ISSUE TITLE
OTA "succeeds" but old firmware still runs

### ISSUE THREAD

**Issue by kilrah** [oarcher/piotech#5]
I have an ESP32C3-based board with esphome flashed, and tried using this component to have it pull new firmware.

This is the log output:

```
[11:42:34][D][ota_http:098]: Trying to connect to http://ha-bracelets.local:8123/local/bracelets_firmware/b105.bin
[11:42:34][V][ota_http:112]: http begin successfull.
[11:42:34][VV][ota_http:116]: http client setReuse.
[11:42:34][V][ota_http:121]: md5sum from received data initialized.
[11:42:34][V][ota_http:125]: http headers collected.
[11:42:34][V][ota_http:131]: http GET finished.
[11:42:34][D][ota_http:145]: firmware is 1172720 bytes length.
[11:42:34][D][ota_http:042]: Using ArduinoESP32OTABackend
[11:42:34][VV][ota_http:158]: Got esp32 stream
[11:42:34][D][ota_http:195]: Progress: 0.1%
[11:42:35][D][ota_http:195]: Progress: 6.4%
[11:42:36][D][ota_http:195]: Progress: 12.7%
[11:42:37][D][ota_http:195]: Progress: 18.9%
[11:42:39][D][ota_http:195]: Progress: 25.2%
[11:42:40][D][ota_http:195]: Progress: 31.5%
[11:42:41][D][ota_http:195]: Progress: 37.6%
[11:42:42][D][ota_http:195]: Progress: 43.7%
[11:42:43][D][ota_http:195]: Progress: 50.7%
[11:42:44][D][ota_http:195]: Progress: 60.7%
[11:42:45][D][ota_http:195]: Progress: 67.5%
[11:42:46][D][ota_http:195]: Progress: 77.4%
[11:42:47][D][ota_http:195]: Progress: 84.3%
[11:42:48][D][ota_http:195]: Progress: 90.5%
[11:42:49][D][ota_http:195]: Progress: 98.9%
[11:42:49][D][ota_http:195]: Progress: 100.0%
[11:42:49][I][ota_http:204]: Done in -185074578797902317207421028936074846135862769981177779226067362725658385491025278032410729529558311763762167874532392951006107027894768590644056147060628029635789192700879247530437045176509745606127680908602101329748211793920 secs
[11:42:49][D][ota_http:209]: md5sum recieved: a0464b0d0d31b4d4c84c6e4fa8e27856 (size 1172720)
[11:42:49][I][ota_http:228]: OTA update finished! Rebooting...
[11:42:49][I][app:134]: Rebooting safely...
```

Everything looks just fine other than... the time, but upon reboot the old firmware is still running. Any idea?

**Comment by oarcher** [comment]
That looks strange. Have you double-checked that the firmware on the http server is not an old one (timestamp, etc ...) ?

Can you also check that the OTA partition change when you do several successful OTA updates ? 
To do that, you will need to set the debug level to `VERY_VERBOSE`, and search the log for something like:
```
[D][Updater.cpp:133] begin(): OTA Partition: app1
```

The log should switch to `app0`, then to `app1`, then to `app0`, etc ...

This behaviour should be the same between the regular OTA and HTTP_OTA (http_ota just call the regular ota backend).


I've pushed a new commit that fix the time overflow.

**Comment by kilrah** [comment]
Yeah I'm sure about the bin, tested multiple times. 
Will check the very verbose log in a couple of days, not close to the hardware anymore right now.

**Comment by kilrah** [comment]
Had to use serial logs, web one doesn't show the OTA partition.

But yeah in the attached log I first do a few OTAs triggered by the ESPHome dashboard and the partitions correctly toggle, then a few from http and it stays stuck on app1

[http_ota.txt](https://github.com/oarcher/piotech/files/12673451/http_ota.txt)

**Comment by oarcher** [comment]
Yes, you have to use serial logs to get full logs.

I don't understand fully your logs, because:
  - There is a lot of 'HTTP/1.1 404 Not Found' http error messages
  - There is no logs from `ota_http`. (They should prefixed with `[ota_http:xxx]`, but there is no occurrence in your logs )
  - The device seems to reboot before the ota ends.

Can you modify the `esphome` section of your yaml to print a boot message ?

```yaml
esphome:
  on_boot:
    priority: -100
    then:
      - logger.log: "device boot"
```

And we must found why no `ota_http` logs are displayed. Can you add a log message before the ota starts ?
```yaml
button:
  - platform: template
    name: "Firmware update"
    on_press:
      then:
        - logger.log: "calling ota_http.flash"
        - ota_http.flash:
            url: http://example.com/firmware.bin
        - logger.log: "This message should be not displayed(reboot)"
```

**Comment by kilrah** [comment]
> There is a lot of 'HTTP/1.1 404 Not Found' http error messages

The device checks for an update using ota_http at boot, and for this part of the logs where I did OTAs from the dashboard there was no update file present

> There is no logs from ota_http. (They should prefixed with [ota_http:xxx], but there is no occurrence in your logs )

These are logs from the device's USB serial port, as I mentioned the "OTA Partition: appX" did not show up in the web log. The serial log however does not contain the ota_http output, but it is there in the web log (what I gave in the first post)

**Comment by oarcher** [comment]
In my case, when using serial logs, I've got both `ota_http` logs and verbose logs. Can you try to call `ota_http` in the simplest way, ie not at boot time but with a button, like my example before ?

Can you give also your boot configuration that fetch the firmware and flash it ? I will try it to check if there is some differences with the simplest way.

Also, try to put a very simple `firmware.bin` on the http server (ie no `ota_http`, no boot option, etc...)

**Comment by kilrah** [comment]
> In my case, when using serial logs, I've got both ota_http logs and verbose logs

It might be because I'm on a C3... from esphome's logger doc the USB port on that is `USB_SERIAL_JTAG`, but if I try to specify it as  `hardware_uart` in the logger component it tells me that's only supported with the `esp-idf` framework, which ota_http doesn't support so I'm in a catch-22. The output I get is likely the core stuff but nothing from esphome itself. Will need to whip out a serial adapter to connect to the hardware uart and see what I need to get that running.

> Can you give also your boot configuration that fetch the firmware and flash it ? I will try it to check if there is some differences with the simplest way.

```
- platform: status
    id: connected
    on_press:
      then:
      - delay: 5s
      - ota_http.flash:
          url: http://ha-bracelets.local:8123/local/bracelets_firmware/b666.bin
          verify_ssl: false
```

**Comment by oarcher** [comment]
I was thinking from your previous message that the flash was done in the `on_boot` section.

Do you have something like:

```yaml
esphome:
  # ...
  on_boot:
    priority: 800
    then:
      - button.press: connected
```

Nevertheless, this might be a C3 issue, as the hardware is different from the regular esp32. Are you able to test it on a non-C3 device ?

On my side, I will try to get a C3 to play with it.

**Comment by kilrah** [comment]
> Do you have something like

Nope, `status` is a `binary_sensor` that comes from esphome and signals whether it's connected to HA.
https://esphome.io/components/binary_sensor/status.html

OK I've found the hardware UART and do get the full expected log now. Here is one and both yaml for what's on the device with a template button to trigger as per sample, and what's on the server without any external_components. Device lights the led blue and the firmware that is supposed to be fetched should be green, but that never happens (and the OTA partition never toggles).

Stupid question, but we're clear that the firmware on the server is the one we get from "manual download - modern format" in the esphome dashboard and not some other version that'd need to be generated differently, right?

{log removed because not sanitized and no longer needed}
[on_device.txt](https://github.com/oarcher/piotech/files/12683902/on_device.txt)
[on_server.txt](https://github.com/oarcher/piotech/files/12683904/on_server.txt)

I should be able to try with a regular esp32, just need to find one... Got mostly C3s and S3s nowadays. 

It's weird since OTA from the dashboard works fine, Could there be a "close()" or something that needs to be called to terminate the process?

**Comment by kilrah** [comment]
> Stupid question, but we're clear that the firmware on the server is the one we get from "manual download - modern format" in the esphome dashboard and not some other version that'd need to be generated differently, right?

Ugh, no it's not...
Digging into the build dir esphome generates `firmware.bin` and `firmware-factory.bin`. 
"Modern format" downloads the latter and this doesn't work, causing apparent success but somehow silently not updating the boot partition, or that version maybe forcing it.
`firmware.bin` works. That is what gets downloaded by "Legacy format".

Leaving open since it warrants being documented.

**Comment by oarcher** [comment]
Sure, this needs to be documented! I've never tried with the esphome ha dashboard,  just with the cli.

Unfortunately, and because the flash backend allow gzipped firmware (see https://github.com/oarcher/piotech/issues/1#issuecomment-1648456046 ), I won't be able to check the type of the file.
